# Generated by Django 4.2.14 on 2024-09-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_rentalitem_delete_todoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
