# Generated by Django 4.2.14 on 2024-08-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('available', models.BooleanField(default=True)),
                ('renter_first_name', models.CharField(max_length=50)),
                ('renter_last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
